apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm
  labels:
    app: myecomm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomm-pod
  template:
    metadata:
      labels:
        app: ecomm-pod
    spec:
      containers:
        - name: ecomm-pod
          image: suryahosur/myecomm
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: ecomm-pod
  ports:
    - port: 80
      targetPort: 80
      

